### PR TITLE
Sbhat oim topology

### PR DESCRIPTION
**Pull request by shreyb**
This is the code to get the OIM Topology information into GRACC records.  The method in the OIMTopology class in OIMTopology.py, generate_dict_for_gracc, is structured to return dictionaries similar to what Derek's parseDoc method does for the OIM Projects information.

### CODE REVIEW

**Comment by shreyb** [comment]
Derek had two comments:

1)  We reprocess the data all the time, so a cache file is unnecessary.  Plus, we'd need to put file locks in place to make sure parallel processes aren't overwriting the file while it's being read.  It's easier just to forget about the cache.  If we have problems with OIM connectivity (the reason the cache file was there in the first place), we'll be fine for 7 days, as we reprocess records often enough. Note:  I'll have to change my unittest module too then.

2)  Add to this pull request the lines that would need to be added to summary_replayer.py to get this to work.

**Comment by shreyb** [comment]
All of the updates Derek mentioned are finished.  I'll be attaching the new mapping test file here and in the JIRA ticket (with 1000 records checked) after my latest test (where I run that test 10 times - so 10000 records total) is done.

**Comment by djw8605** [comment]
I don't think you added the lines to summary_replayer.py yet.

**Comment by shreyb** [comment]
Yep - I just put those in now.

**Comment by djw8605** [comment]
It appears the jobs are failing here: https://travis-ci.org/opensciencegrid/gracc-request/builds/161981602#L3082

```
Sep 22 18:34:04 4dec6d74ce43 graccreq[992]: ERROR:root:Exception caught in query ES: 'ProbeName'
Sep 22 18:34:04 4dec6d74ce43 graccreq[992]: ERROR:root:Traceback (most recent call last):
Sep 22 18:34:04 4dec6d74ce43 graccreq[992]: File "/usr/lib/python2.7/site-packages/graccreq/summary_replayer.py", line 49, in run
Sep 22 18:34:04 4dec6d74ce43 graccreq[992]: self.addProperties(record)
Sep 22 18:34:04 4dec6d74ce43 graccreq[992]: File "/usr/lib/python2.7/site-packages/graccreq/summary_replayer.py", line 69, in addProperties
Sep 22 18:34:04 4dec6d74ce43 graccreq[992]: topology_doc = self.topology.generate_dict_for_gracc(record)
Sep 22 18:34:04 4dec6d74ce43 graccreq[992]: File "/usr/lib/python2.7/site-packages/graccreq/oim/OIMTopology.py", line 191, in generate_dict_for_gracc
Sep 22 18:34:04 4dec6d74ce43 graccreq[992]: probe_fqdn = re.match('.+:(.+)', doc['ProbeName']).group(1)
Sep 22 18:34:04 4dec6d74ce43 graccreq[992]: KeyError: 'ProbeName'
Sep 22 18:34:04 4dec6d74ce43 graccreq[992]: ERROR:root:Traceback (most recent call last):
Sep 22 18:34:04 4dec6d74ce43 graccreq[992]: File "/usr/lib/python2.7/site-packages/graccreq/summary_replayer.py", line 20, in SummaryReplayerFactory
Sep 22 18:34:04 4dec6d74ce43 graccreq[992]: replayer.run()
Sep 22 18:34:04 4dec6d74ce43 graccreq[992]: File "/usr/lib/python2.7/site-packages/graccreq/summary_replayer.py", line 54, in run
Sep 22 18:34:04 4dec6d74ce43 graccreq[992]: raise e
Sep 22 18:34:04 4dec6d74ce43 graccreq[992]: KeyError: 'ProbeName'
```

**Comment by shreyb** [comment]
Alright - this should have fixed those errors we saw in the CI test.

**Comment by shreyb** [comment]
Good - I'm going to make one more (purely stylistic) change, commit that within the hour, and hopefully it should also pass tests.  Then, is there anything else we need before merging this in?

**Comment by djw8605** [comment]
Nope I think this is all the changes that are needed.  I'll watch for the new commit.

**Review by djw8605 — APPROVED** [review]
Looks great!  I'll put together an updated RPM and deploy it.

**Pull request merged**
