### PR TITLE
Add new IDs and mappings

### PR DESCRIPTION
**Pull request by CannonLock**
- Added FieldOfScienceID
  - Add Broad, Major, and Detailed categories corresponding to new ID
- Add InstitutionID to projects and facilities

### CODE REVIEW

**Comment by djw8605** [comment]
I don't love the idea of committing an xlsx file to the git repo.  Any way around that?

Otherwise, I think it looks ok.

**Comment by CannonLock** [comment]
Depends on this: https://github.com/opensciencegrid/topology/pull/4131

**Comment by CannonLock** [comment]
@djw8605 Do you have anything in mind? 

I also cringed at committing the spreadsheet, but I couldn't think of a better way to do it.

The spreadsheet comes from NSF, and I liked the idea of not needing a network request for a static 80kb file. 

I can convert it to a json so that it is more machine readable and remove the new dependencies.

**Comment by CannonLock** [comment]
Do I need to do anything to allow the ability to do updates. So if a InstitutionName associated with the InstitutionID changes it gets updated in past records?

Or ( and this shouldn't ever happen ) if a FieldOfScienceID changes entirely.

**Comment by djw8605** [comment]
> I can convert it to a json so that it is more machine readable and remove the new dependencies.

Even a CSV is better, don't have to go so far as json.  But, if the original source is xlsx, then it's probably fine to keep it xlsx.  Could you try building the docker container though, just to make sure all the new requirements work inside the minimal container that gracc-request uses.

Maybe add a README.md to the directory with the xlsx saying where it came from (URL) and why it was kept xlsx?

> Do I need to do anything to allow the ability to do updates. So if a InstitutionName associated with the InstitutionID changes it gets updated in past records?

You don't need to do anything.  There is a cron on tiger that re-summarizes the last year, and will overwrite the records with new the new updated values every day.  So you don't need to do anything special.

**Comment by CannonLock** [comment]
@djw8605 Okay this is ready for review.

**Comment by djw8605** [comment]
Just checking, have you tried building this in the docker file?  Want to make sure it works in the minimum python environment that gracc-request is built.

**Comment by CannonLock** [comment]
@djw8605 Yes I have.

I had to add `setuptools` to get it to build. That seemed atypical to me. 

`
docker build -t gracc-request .

[+] Building 21.8s (12/12) FINISHED                                                                                                                                                                                                             docker:desktop-linux
 => [internal] load .dockerignore                                                                                                                                                                                                                               0.1s
 => => transferring context: 2B                                                                                                                                                                                                                                 0.0s
 => [internal] load build definition from Dockerfile                                                                                                                                                                                                            0.1s
 => => transferring dockerfile: 337B                                                                                                                                                                                                                            0.0s
 => [internal] load metadata for docker.io/library/python:3-alpine                                                                                                                                                                                              1.2s
 => [auth] library/python:pull token for registry-1.docker.io                                                                                                                                                                                                   0.0s
 => [internal] load build context                                                                                                                                                                                                                               2.7s
 => => transferring context: 131.35MB                                                                                                                                                                                                                           2.7s
 => [1/6] FROM docker.io/library/python:3-alpine@sha256:7130f75b1bb16c7c5d802782131b4024fe3d7a87ce7d936e8948c2d2e0180bc4                                                                                                                                        2.7s
 => => resolve docker.io/library/python:3-alpine@sha256:7130f75b1bb16c7c5d802782131b4024fe3d7a87ce7d936e8948c2d2e0180bc4                                                                                                                                        0.0s
 => => sha256:a40a09e513fcceff78cac5c5ebf688fa62abd101128d2d4278da028e5ebf1e3f 250B / 250B                                                                                                                                                                      0.1s
 => => sha256:7130f75b1bb16c7c5d802782131b4024fe3d7a87ce7d936e8948c2d2e0180bc4 9.02kB / 9.02kB                                                                                                                                                                  0.0s
 => => sha256:3f4a13bc190eece4761437ee7820cbe6e3226616341e92bf7bea1d004731aa29 1.74kB / 1.74kB                                                                                                                                                                  0.0s
 => => sha256:029bbec31d2e920995f23b70a5d745cb18ee721cb45170b6fc3e97f90c87ed04 4.85kB / 4.85kB                                                                                                                                                                  0.0s
 => => sha256:72912374a9bef37c7dbcaa7fe9b00887ac272e3d88f4bb544bcd5502dec65ae7 13.26MB / 13.26MB                                                                                                                                                                0.5s
 => => extracting sha256:72912374a9bef37c7dbcaa7fe9b00887ac272e3d88f4bb544bcd5502dec65ae7                                                                                                                                                                       2.0s
 => => extracting sha256:a40a09e513fcceff78cac5c5ebf688fa62abd101128d2d4278da028e5ebf1e3f                                                                                                                                                                       0.0s
 => [2/6] ADD . /gracc-request                                                                                                                                                                                                                                  1.8s
 => [3/6] WORKDIR /gracc-request                                                                                                                                                                                                                                0.0s
 => [4/6] RUN pip install -r requirements.txt                                                                                                                                                                                                                  14.0s
 => [5/6] RUN python setup.py install                                                                                                                                                                                                                           0.5s 
 => [6/6] RUN install -d -m 0755 /etc/graccreq/config.d/ && install -m 0744 config/gracc-request.toml /etc/graccreq/config.d/gracc-request.toml                                                                                                                 0.3s 
 => exporting to image                                                                                                                                                                                                                                          1.0s 
 => => exporting layers                                                                                                                                                                                                                                         1.0s 
 => => writing image sha256:6d8f0e3c7d5839849dd35054545f25a24741b03081bf718d175d015a8552a180                                                                                                                                                                    0.0s 
 => => naming to docker.io/library/gracc-request                                                                                                                                                                                                                0.0s 
                                                                                                                                                                                                                                                                     
View build details: docker-desktop://dashboard/build/desktop-linux/desktop-linux/qjxzbkgz9t6zcztf1wqik7y4q
`

**Comment by CannonLock** [comment]
I am unclear on running the `test_inside_docker.sh` script however

**Pull request merged**
