### PR TITLE
Bug fix for cache file

### PR DESCRIPTION
**Pull request by shreyb**
When deciding whether or not to create a new Cache file for OIM Topology, the current time used to be evaluated when the module itself was loaded, not when the OIMTopology class was instantiated.  Therefore, as long as a worker was alive, the cachefile didn't get updated. I moved the evaluation of the time (variable curtime) into the function within OIMTopology called read_from_cache, where we decide whether or not to read the currently-stored cache file.

If this passes unit tests, we should probably deploy this as soon as possible - it's a pretty important oversight that's completely on me.

### CODE REVIEW

**Comment by djw8605** [comment]
Looks good to me.  I'll wait for the Travis tests to complete, then merge it.

**Comment by shreyb** [comment]
Is this good to merge?

**Comment by djw8605** [comment]
Yup, sorry.

**Comment by shreyb** [comment]
No worries.  Thanks!

**Pull request merged**
