### PR TITLE
Move OIM URLs into toml config file

### PR DESCRIPTION
**Pull request by shreyb**
Added OIM URL config file items.  I changed the behavior so that the summary replayer passes in the self._config item to the applicable class.

The classes themselves now accept a url parameter.  If this is not set, then they default to using the url specified at the top of the class.

### CODE REVIEW

**Comment by djw8605** [comment]
I think you need to add these OIM lines to the testing configuration in tests/ directory.

**Comment by shreyb** [comment]
Ah - I'll look into that then. Thanks!

**Comment by shreyb** [comment]
So it looks like the CI check failed when trying to do an apt-get update.  I don't think that's due to the changes I'm proposing, right?

**Comment by djw8605** [comment]
Nope, not your fault.  I restarted the build.

**Comment by shreyb** [comment]
Great - thanks!

**Pull request merged**
