### PR TITLE
New myosg

### PR DESCRIPTION
**Pull request by djw8605**
## Do not merge

Using my-itb.opensciencegrid.org

### CODE REVIEW

**Review by retzkek — COMMENTED** [review]
Why is this necessary? Edit: specifically I'm referring to c025601 "Fixing user agent for getting OIM info".

**Comment by djw8605** [comment]
Ah, yes.  The user agent is so that cloudflare doesn't block us if we are going through them for the topology information.  In the future, we plan to place the cloudflare CDN in front of this interface, so it's probably good to keep.  As well as distribute it to the other places we download OIM data.

**Comment by retzkek** [comment]
Instead of spoofing headers on the client side couldn't you just disable the browser integrity check in CloudFlare? Isn't the point of that to *catch* this sort of behavior, so you're running the risk of tripping it in the future and aiming for a moving target?

**Comment by djw8605** [comment]
This comment made me look through all of the cloudflare firewall settings, and I found this: "Browser Integrity Check".  I believe this is the cause of the blocking.

It has happened many times in the past that the python urllib user agent isn't allowed.  I think heroku by default stops it.  But at least we can stop cloudflare from hitting this problem.

**Pull request merged**
